### ISSUE TITLE
SAP in dataproduct identifier

### ISSUE THREAD

**Issue by SterVeen** [brentjens/lofar-obs-xml#4]
Can you push the SAP in dataproduct identifier to the github version? Then we can test genvalobs + pipelines.

**Comment by brentjens** [comment]
I think it is already there.

- Michiel

SterVeen writes:

> Can you push the SAP in dataproduct identifier to the github version? Then we can test genvalobs +
> pipelines.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Dr. Michiel A. Brentjens
Senior Observatory Astronomer
Astron Netherlands Institute for Radio Astronomy
Oude Hoogeveensedijk 4
7991 PD Dwingeloo
The Netherlands
Office:    (+31) (0)521 - 595 781
Reception: (+31) (0)521 - 595 100
brentjens@astron.nl
http://www.astron.nl/~brentjens/
